// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.basic.crudapp.domain;

import com.basic.crudapp.domain.RecordIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RecordIntegrationTest_Roo_Configurable {
    
    declare @type: RecordIntegrationTest: @Configurable;
    
}
