// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.basic.crudapp.domain;

import com.basic.crudapp.domain.RecordDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RecordDataOnDemand_Roo_Configurable {
    
    declare @type: RecordDataOnDemand: @Configurable;
    
}
