// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.basic.crudapp.domain;

import com.basic.crudapp.domain.RecordDataOnDemand;
import com.basic.crudapp.domain.RecordIntegrationTest;
import com.basic.crudapp.repo.RecordRepo;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.bson.types.ObjectId;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect RecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RecordIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/testApplicationContext*.xml");
    
    @Autowired
    RecordDataOnDemand RecordIntegrationTest.dod;
    
    @Autowired
    RecordRepo RecordIntegrationTest.recordRepo;
    
    @Test
    public void RecordIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = recordRepo.count();
        Assert.assertTrue("Counter for 'Record' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RecordIntegrationTest.testFind() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        ObjectId id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = recordRepo.findOne(id);
        Assert.assertNotNull("Find method for 'Record' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Record' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RecordIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = recordRepo.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Record', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Record> result = recordRepo.findAll();
        Assert.assertNotNull("Find all method for 'Record' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Record' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RecordIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        long count = recordRepo.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Record> result = recordRepo.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Record' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Record' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RecordIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", dod.getRandomRecord());
        Record obj = dod.getNewTransientRecord(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Record' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Record' identifier to be null", obj.getId());
        try {
            recordRepo.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Record' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RecordIntegrationTest.testDelete() {
        Record obj = dod.getRandomRecord();
        Assert.assertNotNull("Data on demand for 'Record' failed to initialize correctly", obj);
        ObjectId id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Record' failed to provide an identifier", id);
        obj = recordRepo.findOne(id);
        recordRepo.delete(obj);
        Assert.assertNull("Failed to remove 'Record' with identifier '" + id + "'", recordRepo.findOne(id));
    }
    
}
